version: '3.7'

services:
  
  consul-server1:
    image: hashicorp/consul-enterprise:1.11.1-ent
    env_file:
      - .env
    environment:
      CONSUL_HTTP_ADDR: "consul-server1:8500"
      CONSUL_HTTP_TOKEN: "secret"
    container_name: consul-server1
    restart: always
    volumes:
     - ./server1.json:/consul/config/server1.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: hashicorp/consul-enterprise:1.11.1-ent
    env_file:
      - .env
    environment:
      CONSUL_HTTP_ADDR: "consul-server2:8500"
      CONSUL_HTTP_TOKEN: "secret"
    container_name: consul-server2
    restart: always
    volumes:
     - ./server2.json:/consul/config/server2.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: hashicorp/consul-enterprise:1.11.1-ent
    env_file:
      - .env
    environment:
      CONSUL_HTTP_ADDR: "consul-server3:8500"
      CONSUL_HTTP_TOKEN: "secret"
    container_name: consul-server3
    restart: always
    volumes:
     - ./server3.json:/consul/config/server3.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-client1:
    image: hashicorp/consul-enterprise:1.11.1-ent
    env_file:
      - .env
    environment:
      CONSUL_HTTP_ADDR: "consul-client1:8500"
      CONSUL_HTTP_TOKEN: "secret"
    container_name: consul-client1
    restart: always
    volumes:
     - ./client1.json:/consul/config/client.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8501:8500"
    command: "agent"

  consul-client2:
    image: hashicorp/consul-enterprise:1.11.1-ent
    env_file:
      - .env
    environment:
      CONSUL_HTTP_ADDR: "consul-client2:8500"
      CONSUL_HTTP_TOKEN: "secret"
    container_name: consul-client2
    restart: always
    volumes:
     - ./client2.json:/consul/config/client.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8502:8500"
    command: "agent"

  consul-client3:
    image: hashicorp/consul-enterprise:1.8.19-ent
    env_file:
      - .env
    environment:
      CONSUL_HTTP_ADDR: "consul-client3:8500"
      CONSUL_HTTP_TOKEN: "secret"
    container_name: consul-client3
    restart: always
    volumes:
     - ./client3.json:/consul/config/client.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8503:8500"
    command: "agent"

networks:
  consul:
    driver: bridge

